# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('test_number', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Choices')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('Ph_no', models.IntegerField()),
                ('mail_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='exam_table',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Questions'),
        ),
        migrations.AddField(
            model_name='exam_table',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.User_Data'),
        ),
        migrations.AddField(
            model_name='choices',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Questions'),
        ),
    ]
