# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Choices')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Questions')),
            ],
        ),
    ]
