# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='panswers',
            field=models.CharField(default='DefaultPythonAnswer', max_length=250),
        ),
        migrations.AddField(
            model_name='questions',
            name='pquestion',
            field=models.CharField(default='DefaultPythonQueston', max_length=1000),
        ),
    ]
