# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_auto_20160922_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('c1', models.CharField(max_length=500)),
                ('c2', models.CharField(max_length=500)),
                ('c3', models.CharField(max_length=500)),
                ('c4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='choices',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='exam_table',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='exam_table',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='exam_table',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='course',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='question_id',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Exam_Table',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='User_Data',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Course'),
        ),
    ]
